name: .NET Build

on:
  workflow_dispatch: # 手動でビルドボタンを押せるようにする設定

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # 最新の.NET 8環境をセットアップします

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Il2CppDumper-latest
        path: |
          Il2CppDumper/bin/Release/net*/
